//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toyoda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int idDocumento { get; set; }
        public Nullable<int> idTipoDocumento { get; set; }
        public string numDocumento { get; set; }
        public Nullable<int> idPersona { get; set; }
    }
}
