//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toyoda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoCliente
    {
        public int idTipoCliente { get; set; }
        public string tipoCliente1 { get; set; }
    }
}
